name: LimitedClones
version: 1.1
main: honeb1.limitedclones.LimitedClones
api-version: 1.16
softdepend: [PlaceholderAPI,WorldGuard]

permissions:
  limitedclones.modify:
    default: op
  limitedclones.bypass:
    default: op
  limitedclones.help:
    default: op

commands:
 clones:
   #サブコマンド
   #set, heal, add, help
